--QUIZ
use [CENTERO-1]

-- 답안 1.
SELECT ISNULL(ISNULL(A.Credit_Proponent_ID, A.TRD_TP), 'TOTAL') AS COL_TP, A.TRD_SUM
	FROM (
		SELECT Credit_Proponent_ID, TRD_TP, SUM(Credit_Size) AS TRD_SUM
		FROM TB_TRD_TRADING_LEDGER
		GROUP BY GROUPING SETS(Credit_Proponent_ID, TRD_TP, ())
	) AS A

-- 번외) 임시테이블 사용
CREATE TABLE #TABLE(
	Credit_Proponent_ID nvarchar(50)
	,TRD_TP nvarchar(50)
	,TRD_SUM bigint NOT NULL
)

INSERT INTO #TABLE
	SELECT Credit_Proponent_ID, TRD_TP, SUM(Credit_Size) AS TRD_SUM
		FROM TB_TRD_TRADING_LEDGER
		GROUP BY GROUPING SETS(Credit_Proponent_ID, TRD_TP, ())

SELECT ISNULL(ISNULL(Credit_Proponent_ID, TRD_TP), 'TOTAL') AS COL_TP, TRD_SUM
	FROM #TABLE

-- 답안 3. UNION ALL
SELECT ISNULL(TRD_TP, 'TOTAL') AS COL_TP, SUM(Credit_Size) AS TRD_SUM
	FROM TB_TRD_TRADING_LEDGER
	GROUP BY GROUPING SETS(TRD_TP, ())
UNION ALL
SELECT Credit_Proponent_ID AS COL_TP, SUM(Credit_Size) AS TRD_SUM
	FROM TB_TRD_TRADING_LEDGER
	GROUP BY Credit_Proponent_ID